#!/bin/bash
###
if [ `git rev-parse --abbrev-ref HEAD` == "master" ]; then
	LAYOUT_PREFIX='---\r\nlayout: index\r\n---\r\n\r\n'

	git checkout gh-pages
	git checkout master -- README.md
	echo -e $LAYOUT_PREFIX > index.md
	cat README.md >> index.md
	git rm README.md -f
	git add index.md
	git commit -m "Sync README.md from master into index.md"

	git checkout master
fi
